In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
df=pd.read_csv('Data.csv')

In [24]:
# we used the catagorica col or data nd we used that cols to fill randomly

In [25]:
df

    FireplaceQu GarageQual  SalePrice
0           NaN         TA     140295
1           NaN         TA     119007
2            TA         TA     136737
3            TA         TA     109913
4            Gd         TA     177281
..          ...        ...        ...
795         NaN         TA     144226
796         NaN         TA     173308
797         NaN         Gd      89348
798         NaN         Gd     134397
799          Fa         Fa     149794

[800 rows x 3 columns]

In [26]:
df.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     140295
1         NaN         TA     119007
2          TA         TA     136737
3          TA         TA     109913
4          Gd         TA     177281

In [27]:
df.isnull().mean()*100

FireplaceQu    47.25
GarageQual      5.50
SalePrice       0.00
dtype: float64

In [28]:
x=df
y=df['SalePrice']

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['SalePrice']),df['SalePrice'],test_size=0.2,random_state=42)

In [31]:
x_train['impu_GarageQual']=x_train['GarageQual']
x_train['impu_Fireplace']=x_train['FireplaceQu']
x_test['impu_GarageQual']=x_test['GarageQual']
x_test['impu_Fireplace']=x_test['FireplaceQu']

In [32]:
x_train.sample(6)

    FireplaceQu GarageQual impu_GarageQual impu_Fireplace
649          TA         TA              TA             TA
748          Fa         Gd              Gd             Fa
56          NaN         Gd              Gd            NaN
476         NaN         TA              TA            NaN
138          Gd         Gd              Gd             Gd
307         NaN         TA              TA            NaN

In [33]:
x_train['impu_GarageQual'][x_train['impu_GarageQual'].isnull()]=x_train['GarageQual'].dropna().sample(x_train['GarageQual'].isnull().sum()).values
x_test['impu_GarageQual'][x_test['impu_GarageQual'].isnull()]=x_train['GarageQual'].dropna().sample(x_test['GarageQual'].isnull().sum()).values
x_train['impu_Fireplace'][x_train['impu_Fireplace'].isnull()]=x_train['FireplaceQu'].dropna().sample(x_train['FireplaceQu'].isnull().sum()).values
x_test['impu_Fireplace'][x_test['impu_Fireplace'].isnull()]=x_train['FireplaceQu'].dropna().sample(x_test['FireplaceQu'].isnull().sum()).values

C:\Users\HEC\AppData\Local\Temp\ipykernel_6684\2732773297.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train['impu_GarageQual'][x_train['impu_GarageQual'].isnull()]=x_train['GarageQual'].dropna().sample(x_train['GarageQual'].isnull().sum()).values
C:\Users\HEC\AppData\Local\Temp\ipykernel_6684\2732773297.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_test['impu_GarageQual'][x_test['impu_GarageQual'].isnull()]=x_train['GarageQual'].dropna().sample(x_test['GarageQual'].isnull().sum()).values
C:\Users\HEC\AppData\Local\Temp\ipykernel_6684\2732773297.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_train['impu_Fireplace'][x_train['impu_Fireplace'].isnull()]=x_train['FireplaceQu'].dropna().sample(x_train['FireplaceQu'].isnull().sum()).values
C:\Users\HEC\AppData\Local\Temp\ipykernel_6684\2732773297.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_test['impu_Fireplace'][x_test['impu_Fireplace'].isnull()]=x_train['FireplaceQu'].dropna().sample(x_test['FireplaceQu'].isnull().sum()).values

In [34]:
x_train

    FireplaceQu GarageQual impu_GarageQual impu_Fireplace
264          Fa         TA              TA             Fa
615          Fa         Fa              Fa             Fa
329         NaN         TA              TA             Fa
342          Gd         TA              TA             Gd
394         NaN         Gd              Gd             Gd
..          ...        ...             ...            ...
71          NaN         TA              TA             Ex
106         NaN         TA              TA             TA
270          Fa         TA              TA             Fa
435         NaN         TA              TA             TA
102          Gd         TA              TA             Gd

[640 rows x 4 columns]

In [36]:
x_train.isnull().sum()

FireplaceQu        297
GarageQual          35
impu_GarageQual      0
impu_Fireplace       0
dtype: int64

In [37]:
# now see the the neew cols the missing value is full from random values

In [38]:
temp=pd.concat([
    x_train['FireplaceQu'].value_counts()/len(x_train['FireplaceQu'].dropna()),
    x_train['impu_Fireplace'].value_counts()/len(df)
],axis=1)
temp.columns=['orignal','imputed']
temp

     orignal  imputed
TA  0.387755  0.31375
Gd  0.317784  0.25375
Fa  0.172012  0.13750
Ex  0.069971  0.05625
Po  0.052478  0.03875

In [39]:
#see the before and after the values filling the concat is